### ISSUE TITLE
broken in vim

### ISSUE THREAD

**Issue by mockturtl** [sampson-chen/sack#38]
``` sh
$ sag foo
# ...results...
$ F 1
# vim opens to an empty buffer, for file ""/my/actual/desired/file""
```

I believe the cause is the escaped quotes around `$sack__file`, added in the last commit.  [@db5526e](https://github.com/sampson-chen/sack/commit/db5526e38de9aec7f989eb9f2f32f1ed0c3e428b#diff-6829d8e042b2795a6f7fde0e7af4f233L164)

Without them, `F 1` behaves as expected.

**Comment by sampson-chen** [comment]
Thanks, reverted https://github.com/sampson-chen/sack/pull/39

**Comment by partounian** [comment]
@mockturtl If this was fixed, you should close this issue 👍  😄

**Comment by mockturtl** [comment]
:+1: I assume the maintainer(s) know best, but yes, it was resolved.
